---

- set_fact:
    context: "{{ vars.get(role_name, {}) | combine({'role_name': role_name}) }}"


- name: main
  include_role:
    public: yes
    name: common
    tasks_from: main
  vars:
    given: "{{ context }}"


- name: remove default files
  file:
    path: "{{ item }}"
    state: absent
  with_items:
    - "~/.bash_history"
    - "~/.bash_logout"
    - "~/.profile"
    - "~/.bashrc"
