---

- name: bash - main
  include_role:
    public: yes
    name: common
    tasks_from: main
  vars:
    install: "{{ bash.install }}"
    configure: "{{ bash.configure }}"


- name: remove default files
  file:
    path: "{{ item }}"
    state: absent
  with_items:
    - "~/.bash_history"
    - "~/.bash_logout"
    - "~/.profile"
    - "~/.bashrc"
