---

- name: bash - main
  include_role:
    public: yes
    name: common
    tasks_from: main
  vars:
    given: "{{ bash }}"


- name: remove default files
  file:
    path: "{{ item }}"
    state: absent
  with_items:
    - "~/.bash_history"
    - "~/.bash_logout"
    - "~/.profile"
    - "~/.bashrc"
