---

- name: install
  strategy: debug
  hosts: local
  roles:
#   ########### preliminary
    - pre
    - apt
    - snap
    - flatpak
    - kernel

#   ########### terminal
    - bash
#   - zsh
#   - fzf
#   - ssh
#   - git
#   - less
#   - tmux

#   ########### editors
#   - vim
#   - ghostwriter

#   ########### browsers
#   - firefox

#   ########### media
#   - spotify
#   - vlc

#   ########### languages
    - c
#   - python
#   - ruby

#   ########### messaging
#   - signal
#   - telegram

#   ########### gaming
#   - steam
#   - wine

#   ########### development
    - virtualbox
    - vagrant
    - docker

#   ########### postliminary
    - post
