---

- name: apt - main
  include_role:
    public: yes
    name: common
    tasks_from: main
  vars:
    given: "{{ apt }}"


- name: update system
  become: yes
  apt:
    upgrade: dist
    update_cache: yes


- name: install dependencies
  become: yes
  package:
    name: "{{ item }}"
    state: present
  with_items: "{{ apt.dependencies }}"
