---

- set_fact:
    context: "{{ lookup('vars', role_name, default={}) | combine({'role_name': role_name}) }}"


- name: main
  include_role:
    public: yes
    name: common
    tasks_from: main
  vars:
    given: "{{ context }}"

#https://github.com/ValveSoftware/steam-for-linux/issues/3474