---

- set_fact:
    context: "{{ lookup('vars', role_name, default={}) | combine({'role_name': role_name}) }}"


- name: main
  include_role:
    public: yes
    name: common
    tasks_from: main
  vars:
    given: "{{ context }}"


- name: update
  command: "{{ item }} -m pip --no-cache-dir install --upgrade pip"
  with_items:
    - "python2"
    - "python3"
  become: yes