---

- name: ssh - main
  include_role:
    public: yes
    name: common
    tasks_from: main
  vars:
    given: "{{ ssh }}"


- name: remove default ssh path
  file:
    path: "~/.ssh/"
    state: absent


- name: restart sshd
  become: yes
  service:
    name: sshd
    state: restarted
