---

- name: "Update {{ ssh.config.name }} file"
  include_role:
    name: common
    tasks_from: config
  vars:
    given:
      from: "{{ role_path }}"
      name: "{{ ssh.config.name }}"
      path: "{{ ssh.config.path }}"
      file: "{{ ssh.config.file }}"
