---

- name: ssh - update config file
  include_role:
    public: yes
    name: common
    tasks_from: config
  vars:
    src:
      path: "ssh/templates/"
      name: "config"
    dst:
      path: "{{ ssh.config.path }}"
      name: "{{ ssh.config.name }}"