---

- set_fact:
    context: "{{ (lookup('vars', role_name) or {}) | combine({'role_name': role_name}) }}"


- name: main
  include_role:
    public: yes
    name: common
    tasks_from: main
  vars:
    given: "{{ context }}"


- name: remove default ssh path
  file:
    path: "~/.ssh/"
    state: absent


- name: restart ssh service
  become: yes
  service:
    name: ssh
    state: restarted
