---

- set_fact:
    context: "{{ (lookup('vars', role_name) or {}) | combine({'role_name': role_name}) }}"


- name: main
  include_role:
    public: yes
    name: common
    tasks_from: main
  vars:
    given: "{{ context }}"


- name: add remotes
  become: yes
  command: "flatpak remote-add --if-not-exists {{ item }}"
  with_items: "{{ flatpak.remotes }}"
