---

- name: flatpak - main
  include_role:
    public: yes
    name: common
    tasks_from: main
  vars:
    given: "{{ flatpak }}"


- debug:
    msg: turbug


- name: add remotes
  become: yes
  command: "flatpak remote-add --if-not-exists {{ item }}"
  with_items: "{{ flatpak.remotes }}"
