---

- name: zsh - install.self
  include_role:
    public: yes
    name: common
    tasks_from: install
  vars:
    given: "{{ zsh.install.self }}"


- name: zsh - config.self
  include_role:
    public: yes
    name: common
    tasks_from: config
  vars:
    given:
      src:
        path: "zsh/templates/"
        name: "config"
      dst: "{{ zsh.config.self }}"
