---

- name: git - install.self
  include_role:
    public: yes
    name: common
    tasks_from: install
  vars:
    given: "{{ git.install.self }}"


- name: git - config.self
  include_role:
    public: yes
    name: common
    tasks_from: config
  vars:
    given:
      src:
        path: "git/templates/"
        name: "config"
      dst: "{{ git.config.self }}"


- name: git - config.ignore
  include_role:
    public: yes
    name: common
    tasks_from: config
  vars:
    given:
      src:
        path: "git/files/"
        name: "ignore"
      dst: "{{ git.config.ignore }}"
