---

- name: git - config
  include_role:
    public: yes
    name: common
    tasks_from: config
  vars:
    src:
      path: "git/templates/"
      name: "config"
    dst:
      path: "{{ git.config.path }}"
      name: "{{ git.config.name }}"


- name: git - ignore
  include_role:
    public: yes
    name: common
    tasks_from: config
  vars:
    src:
      path: "git/files/"
      name: "ignore"
    dst:
      name: "{{ git.ignore.name }}"
      path: "{{ git.ignore.path }}"