---


- name: update gitconfig file
  include_role:
    name: common
    tasks_from: config
  vars:
    src:
      path: "git/templates/"
      name: "config"
    dst:
      name: "{{ git.config.name }}"
      path: "{{ git.config.path }}"


- name: update gitignore file
  include_role:
    name: common
    tasks_from: config
  vars:
    src:
      path: "git/files/"
      name: "ignore"
      type: file
    dst:
      name: "{{ git.ignore.name }}"
      path: "{{ git.ignore.path }}"
