---

- name: terraform - main
  include_role:
    public: yes
    name: common
    tasks_from: main
  vars:
    given: "{{ terraform }}"


- name: download
  get_url:
    url: "{{ terraform.url }}"
    dest: "/tmp/terraform.zip"


- name: install
  become: yes
  unarchive:
    src: "/tmp/terraform.zip"
    dest: "/usr/local/bin"


- name: clean up
  file:
    path: "/tmp/terraform.zip"
    state: absent
