---

- set_fact:
    context: "{{ lookup('vars', role_name, default={}) | combine({'role_name': role_name}) }}"


- name: main
  include_role:
    public: yes
    name: common
    tasks_from: main
  vars:
    given: "{{ context }}"


- name: download
  get_url:
    url: "{{ terraform.url }}"
    dest: "/tmp/terraform.zip"


- name: install
  become: yes
  unarchive:
    src: "/tmp/terraform.zip"
    dest: "/usr/local/bin"


- name: clean up
  file:
    path: "/tmp/terraform.zip"
    state: absent
