---

- name: pre - main
  include_role:
    public: yes
    name: common
    tasks_from: main
  vars:
    given: "{{ pre }}"


- name: create config path
  file:
    path: "{{ pre.config }}"
    state: directory


- name: create backup path
  file:
    path: "{{ pre.backup | dirname }}"
    state: directory