---

- set_fact:
    context: "{{ lookup('vars', role_name) | combine({'role_name': role_name}) }}"


- name: main
  include_role:
    public: yes
    name: common
    tasks_from: main
  vars:
    given: "{{ context }}"


- name: download package
  get_url:
    url: "{{ keybase.url }}"
    dest: "/tmp/keybase.deb"


- name: install
  become: yes
  command: "apt install keybase.deb"
  args:
    chdir: "/tmp/"


- name: clean up
  file:
    path: "/tmp/keybase.deb"
    state: absent