---

- set_fact:
    context: "{{ (lookup('vars', role_name) or {}) | combine({'role_name': role_name}) }}"


- name: main
  include_role:
    public: yes
    name: common
    tasks_from: main
  vars:
    given: "{{ context }}"


- name: remove previous installation directory
  file:
    path: "{{ user_cache }}/pyenv"
    state: absent


- name: install
  shell: "curl https://pyenv.run | PYENV_ROOT='{{ user_home }}/.cache/pyenv' bash"
  args:
    warn: no
