---

- name: check if config path exists
  stat:
    path: "{{ given.dst.path }}{{ given.dst.name }}"
  register: check_path


- name: check if config file exists
  stat:
    path: "{{ given.dst.path }}{{ given.dst.name }}"
  register: check_name
  when: check_path.stat.exists


- name: create config path
  file:
    path: "{{ given.dst.path }}"
    state: directory
    group: "{{ ansible_user }}"
    owner: "{{ ansible_user }}"
  when: not check_path.stat.exists


- name: create backup path
  file:
    path: "{{ pre.backup.path }}{{ given.src.path }}"
    state: directory
    group: "{{ ansible_user }}"
    owner: "{{ ansible_user }}"
  when: check_name.stat is defined and check_name.stat.exists


- name: backup config file
  copy:
    src: "{{ given.dst.path }}{{ given.dst.name }}"
    dest: "{{ pre.backup.path }}{{ given.src.path.split('/')[0] }}/{{ given.dst.name }}"
    group: "{{ ansible_user }}"
    owner: "{{ ansible_user }}"
  when: check_name.stat is defined and check_name.stat.exists


- name: check if role file exists
  stat:
    path: "{{ playbook_dir }}/roles/{{ given.src.path }}{{ given.src.name | default('.nofile') }}"
  register: check_file
  when: given.src.path is search("/files/")


- name: check if role template exists
  stat:
    path: "{{ playbook_dir }}/roles/{{ given.src.path }}{{ given.src.name | default('.nofile') }}"
  register: check_template
  when: given.src.path is search("/templates/")


- name: update config file from roles file
  copy:
    src: "{{ playbook_dir }}/roles/{{ given.src.path }}{{ given.src.name }}"
    dest: "{{ given.dst.path }}{{ given.dst.name }}"
  when: check_file.stat is defined and check_file.stat.exists


- name: update config file from roles template
  template:
    src: "{{ playbook_dir }}/roles/{{ given.src.path }}{{ given.src.name }}"
    dest: "{{ given.dst.path }}{{ given.dst.name }}"
  when: check_template.stat is defined and check_template.stat.exists
