---

- name: check if mandatory variables are defined
  assert:
    that:
      - _given is defined
      - _given.dst is defined
      - _given.src is defined
      - pre.backup is defined


- name: check if configuration path exists
  stat:
    path: "{{ _given.dst | dirname }}"
  register: check_path


- name: check if configuration file exists
  stat:
    path: "{{ _given.dst }}"
  register: check_name
  when: check_path.stat.exists


- name: create configuration path
  file:
    path: "{{ _given.dst | dirname }}"
    state: directory
    owner: "{{ user_name }}"
    group: "{{ user_name }}"
  when: not check_path.stat.exists


- name: create backup path
  file:
    path: "{{ pre.backup | dirname }}/{{ _given.src.split('/')[0] }}"
    state: directory
    owner: "{{ user_name }}"
    group: "{{ user_name }}"
  when: check_name.stat is defined and check_name.stat.exists


- name: backup configuration file
  copy:
    src: "{{ _given.dst }}"
    dest: "{{ pre.backup | dirname }}/{{ _given.src.split('/')[0] }}/"
    owner: "{{ user_name }}"
    group: "{{ user_name }}"
  when: check_name.stat is defined and check_name.stat.exists


- name: check if role file exists
  stat:
    path: "{{ playbook_dir }}/roles/{{ _given.src | default('.nofile') }}"
  register: check_file
  when: _given.src is search("/files/")


- name: update configuration file from roles file
  become: "{{ _given.become | default('no') }}"
  template:
    src: "{{ playbook_dir }}/roles/{{ _given.src }}"
    dest: "{{ _given.dst }}"
  when: check_file.stat is defined and check_file.stat.exists
