---

- name: check if mandatory variables are defined
  assert:
    that:
      - _given is defined
      - _given.dst is defined
      - _given.src is defined
      - pre.backup is defined


- name: check if configuration path exists
  stat:
    path: "{{ _given.dst | dirname }}"
  register: check_path


- name: check if environment file exists
  stat:
    path: "{{ _given.dst }}"
  register: check_name
  when: check_path.stat.exists


- name: create environment file path
  file:
    path: "{{ _given.dst | dirname }}"
    state: directory
    owner: "{{ user_name }}"
    group: "{{ user_name }}"
  when: not check_path.stat.exists


- name: check if role environment file exists
  stat:
    path: "{{ playbook_dir }}/roles/{{ _given.src | default('.nofile') }}"
  register: check_file
  when: _given.src is search("/files/")


- name: update environment file from roles environment file
  become: "{{ _given.become | default('no') }}"
  template:
    src: "{{ playbook_dir }}/roles/{{ _given.src }}"
    dest: "{{ _given.dst }}"
  when: check_file.stat is defined and check_file.stat.exists


- name: create global environment file
  file:
    path: "{{ common.global_env }}"
    state: touch


- name: check if content of role environment is in global environment file
  lineinfile:
    path: "{{ common.global_env }}"
    regexp: "# -+ {{ context.role_name }} -+ #"
    state: absent
  register: check_line
  check_mode: yes


- name: append content of role environment to global environment file
  blockinfile:
    path: "{{ common.global_env }}"
    block: "{{ lookup('file', _given.dst) }}"
    marker: ""
  when: not check_line.changed
