---

- name: check if mandatory variables are defined
  assert:
    that:
      - _given is defined
      - _given.packages is defined


- name: install www keys
  apt_key:
    url: "{{ item }}"
    state: present
  with_items: "{{ _given.gpgkeys }}"
  when: _given.gpgkeys is defined and (item.startswith('http://') or item.startswith('https://'))


- name: install gpg keys
  apt_key:
    keyring:
    keyserver: "{{ item.split('/')[0] }}"
    id: "{{ item.split('/')[1] }}"
  with_items: "{{ _given.gpgkeys }}"
  when: _given.gpgkeys is defined and (not item.startswith('http://') and not item.startswith('https://'))


- name: install lists
  apt_repository:
    repo: "{{ item }}"
    state: present
  with_items: "{{ _given.lists }}"
  when: _given.lists is defined


- name: update cache
  apt:
    update_cache: yes
  when: _given.lists is defined


- name: install packages
  package:
    name: "{{ item }}"
    state: latest
  with_items: "{{ _given.packages }}"
