---

- name: check if mandatory variables are defined
  assert:
    that:
      - given is defined


- name: install
  include_role:
    public: no
    name: common
    tasks_from: install
    apply:
      become: yes
  vars:
    _given: "{{ _dict_item.value }}"
  with_dict: "{{ given.install }}"
  loop_control:
    loop_var: _dict_item
  when: given.install is defined


- name: template
  include_role:
    public: no
    name: common
    tasks_from: template
  vars:
    _given: "{{ _dict_item.value }}"
  with_dict: "{{ given.template }}"
  loop_control:
    loop_var: _dict_item
  when: given.template is defined


- name: environment
  include_role:
    public: no
    name: common
    tasks_from: environment
  vars:
    _given: "{{ given.environment }}"
  when: given.environment is defined


- name: move
  include_role:
    public: no
    name: common
    tasks_from: move
  vars:
    _given: "{{ _dict_item.value }}"
  with_dict: "{{ given.move }}"
  loop_control:
    loop_var: _dict_item
  when: given.move is defined


- name: registry
  include_role:
    public: no
    name: common
    tasks_from: registry
  vars:
    _given: "{{ _dict_item.value }}"
  with_dict: "{{ given.registry }}"
  loop_control:
    loop_var: _dict_item
  when: given.registry is defined

