---

- name: check if mandatory variables are defined
  assert:
    that:
      - _given is defined
      - _given.src is defined
      - _given.dst is defined


- stat:
    path: "{{ _given.src }}"
  register: check_type


- name: move
  become: "{{ _given.become | default('no') }}"
  command: "mv {{ _given.src | quote }} {{ _given.dst | quote }}"
  when: check_type.stat is defined and check_type.stat.exists
