---

- name: check if mandatory variables are defined
  assert:
    that:
      - _given is defined


- name: apply change in dconf registry
  dconf:
    key: "{{ _given.key }}/{{ item.key }}"
    value: "{{ item.value | string }}"
  with_dict: "{{ _given.value }}"
