---

- set_fact:
    context: "{{ vars.get(role_name, {}) | combine({'role_name': role_name}) }}"


- name: main
  include_role:
    public: yes
    name: common
    tasks_from: main
  vars:
    given: "{{ context }}"


- name: create group
  become: yes
  group:
    name: docker
    state: present


- name: add user to group
  become: yes
  user:
    name: '{{ ansible_user }}'
    groups: docker
    append: yes


- name: enable service
  become: yes
  service:
    name: docker
    enabled: yes


- name: start service
  become: yes
  service:
    name: docker
    state: started
