---

- name: docker - main
  include_role:
    public: yes
    name: common
    tasks_from: main
  vars:
    given: "{{ docker }}"


- name: create group
  become: yes
  group:
    name: docker
    state: present


- name: add user to group
  become: yes
  user:
    name: '{{ ansible_user }}'
    groups: docker
    append: yes


- name: enable docker
  become: yes
  service:
    name: docker
    enabled: yes


- name: start docker
  become: yes
  service:
    name: docker
    state: started
