---

- name: vim - install.self
  include_role:
    public: yes
    name: common
    tasks_from: install
  vars:
    given: "{{ vim.install.self }}"


- name: vim - config.theme
  include_role:
    public: yes
    name: common
    tasks_from: config
  vars:
    given:
      src:
        path: "vim/files/"
        name: "hero.vim"
      dst: "{{ vim.config.theme }}"


- name: vim - config.self
  include_role:
    public: yes
    name: common
    tasks_from: config
  vars:
    given:
      src:
        path: "vim/files/"
        name: "config"
      dst: "{{ vim.config.self }}"
