---

- name: vim - main
  include_role:
    public: yes
    name: common
    tasks_from: main
  vars:
    given: "{{ vim }}"


- name: install plugin manager
  git:
    repo: "https://github.com/VundleVim/Vundle.vim.git"
    dest: "{{ vim.configure.self.dst | dirname }}/bundle/Vundle.vim"


- name: install plugins
  command: vim +PluginInstall +qall
