---

- name: vim - theme
  include_role:
    public: yes
    name: common
    tasks_from: config
  vars:
    src:
      path: "vim/files/"
      name: "hero.vim"
    dst:
      path: "{{ vim.theme.path }}"
      name: "{{ vim.theme.name }}"


- name: vim - config
  include_role:
    public: yes
    name: common
    tasks_from: config
  vars:
    src:
      path: "vim/files/"
      name: "config"
    dst:
      path: "{{ vim.config.path }}"
      name: "{{ vim.config.name }}"
