---

- set_fact:
    context: "{{ vars.get(role_name, {}) | combine({'role_name': role_name}) }}"


- name: main
  include_role:
    public: yes
    name: common
    tasks_from: main
  vars:
    given: "{{ context }}"


- name: install plugin manager
  git:
    repo: "https://github.com/VundleVim/Vundle.vim.git"
    dest: "{{ vim.configure.self.dst | dirname }}/bundle/Vundle.vim"


- name: install plugins
  command: vim +PluginInstall +qall
