---

- name: archive backup path
  archive:
    path: "{{ pre.backup.path }}"
    dest: "{{ pre.backup.path }}{{ pre.backup.name }}"
    format: zip


- name: remove ansible path
  file:
    path: "~/.ansible/"
    state: absent
