---

- name: archive backup path
  archive:
    path: "{{ pre.backup | dirname }}"
    dest: "{{ pre.backup }}"
    format: zip


- name: remove ansible path
  file:
    path: "~/.ansible/"
    state: absent
