---

- name: archive backup directory
  archive:
    path: "{{ pre.backup.path }}"
    dest: "{{ pre.backup.path }}{{ pre.backup.name }}"
    format: zip


- name: clean up after ansible
  file:
    path: "~/.ansible/"
    state: absent
