---

- set_fact:
    context: "{{ (lookup('vars', role_name) or {}) | combine({'role_name': role_name}) }}"


- name: main
  include_role:
    public: yes
    name: common
    tasks_from: main
  vars:
    given: "{{ context }}"


- name: archive backup path
  archive:
    path: "{{ pre.backup | dirname }}"
    dest: "{{ pre.backup }}"
    format: zip


- name: clean cache
  become: yes
  apt:
    autoclean: yes


- name: clean dependencies
  become: yes
  apt:
    autoremove: yes


- name: remove ansible path
  file:
    path: "~/.ansible/"
    state: absent
